### ISSUE TITLE
A18

### ISSUE THREAD

**Issue by kaptain-kavern** [spoonshortage/A_Dog_Said#2]
So I'm back, Hello. Hope you're fine.

Before I'm starting to look into the update, have you already worked on it?

**Comment by spoonshortage** [comment]
hi! yeah I'm already on it

**Comment by kaptain-kavern** [comment]
If you need help, I'm there for once ;-D

Also if it can help, I have this page that lists all changes in XML code between A17 and A18, [here](https://github.com/kaptain-kavern/Core/commit/62775d7766fb368014411b071098973cb62682ff)
